#! /usr/bin/env bash

mkdir build && cd build
# Configure ArgoDSM
cmake -DARGO_DEBUG=${ARGO_DBG} -DARGO_VM=${ARGO_VM} -DARGO_BACKEND_MPI=ON -DARGO_BACKEND_SINGLENODE=ON -DARGO_TESTS=ON -DBUILD_DOCUMENTATION=ON -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc -DCMAKE_INSTALL_PREFIX=../install ../

# Build ArgoDSM
make
