name: CI
on: [push, pull_request]

jobs:
  Build-and-Test:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dbg: [OFF, ON]
        vm: [ANONYMOUS, SHM, MEMFD]
    name: On ${{ matrix.os }} (DBG=${{ matrix.dbg }}, VM=${{ matrix.vm }})
    runs-on: ${{ matrix.os }}
    env:
      ARGO_DBG: ${{ matrix.dbg }}
      ARGO_VM:  ${{ matrix.vm  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz libnuma-dev libopenmpi-dev
      - name: Build ArgoDSM
        run: ./.github/scripts/make_argo.sh
      - name: Install ArgoDSM
        run: make install -C build
      - name: Build external
        run: ./.github/scripts/make_external.sh
      - name: Run test suite
        run: |
          sudo sysctl -w vm.overcommit_memory=1
          make test -C build
      - name: Run external
        run: ./.github/scripts/run_external.sh
